import React, { useState, useEffect } from 'react';
import { AlertTriangle, Check, Loader, ShieldCheck, RefreshCw } from 'lucide-react';
import api from '../services/api';
import toast from 'react-hot-toast';

const SEVERITY_BADGES = {
  critical: 'bg-red-50 border-red-200 text-red-700',
  high: 'bg-orange-50 border-orange-200 text-orange-700',
  medium: 'bg-yellow-50 border-yellow-200 text-yellow-700',
  low: 'bg-blue-50 border-blue-200 text-blue-700',
};

export default function Alerts({ alerts, setAlerts }) {
  const [loading, setLoading] = useState(false);
  const [resolvingId, setResolvingId] = useState(null);

  // Fetch initial unresolved alerts
  const fetchAlerts = async (silent = false) => {
    if (!silent) setLoading(true);
    try {
      const res = await api.getAlerts();
      if (res.success) {
        setAlerts(res.data);
      }
    } catch (err) {
      console.error('Failed to fetch alerts:', err);
      toast.error('Failed to sync alerts feed.');
    } finally {
      setLoading(false);
    }
  };

  // Poll alerts every 5 seconds as a fallback, as requested in requirements
  useEffect(() => {
    fetchAlerts();
    const interval = setInterval(() => {
      fetchAlerts(true);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  const handleResolve = async (id) => {
    setResolvingId(id);
    try {
      const res = await api.resolveAlert(id);
      if (res.success) {
        toast.success('Alert resolved successfully.');
        setAlerts((prev) => prev.filter((a) => a.id !== id));
      }
    } catch (err) {
      console.error('Failed to resolve alert:', err);
      toast.error('Could not resolve alert.');
    } finally {
      setResolvingId(null);
    }
  };

  const formatDateTime = (timestamp) => {
    const d = new Date(timestamp);
    return `${d.toLocaleDateString()} ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' })}`;
  };

  return (
    <div className="space-y-6">
      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-800 tracking-wide uppercase flex items-center space-x-2">
            <AlertTriangle className="h-6 w-6 text-red-500" />
            <span>Alerts Control Console</span>
          </h1>
          <p className="text-xs text-slate-500 font-medium">
            Review and resolve diagnostic alert events generated by the simulator
          </p>
        </div>
        <button
          onClick={() => fetchAlerts()}
          disabled={loading}
          className="bg-white hover:bg-slate-50 border border-panelBorder p-2 rounded-lg text-slate-400 hover:text-slate-800 transition-all disabled:opacity-50 shadow-sm"
          title="Manual Refresh"
        >
          <RefreshCw className={`h-4.5 w-4.5 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Main Console Table */}
      <div className="bg-white border border-panelBorder rounded-2xl overflow-hidden shadow-sm select-none">
        {loading ? (
          <div className="py-24 flex flex-col items-center justify-center space-y-3">
            <Loader className="h-8 w-8 text-accentBlue animate-spin" />
            <span className="text-sm text-slate-500 font-semibold">Retrieving unresolved alert events...</span>
          </div>
        ) : alerts.length === 0 ? (
          <div className="py-20 flex flex-col items-center justify-center text-center p-6 space-y-4">
            <div className="bg-green-50 border border-green-200 p-5 rounded-full text-green-600">
              <ShieldCheck className="h-12 w-12" />
            </div>
            <div>
              <p className="text-base font-bold text-slate-800">All Alerts Resolved</p>
              <p className="text-xs text-slate-400 max-w-sm mt-1 mx-auto font-medium">
                No active anomalies or warning notifications found. Keep up the good work!
              </p>
            </div>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-panelBorder bg-slate-50 text-[11px] font-extrabold uppercase tracking-wider text-slate-500">
                  <th className="py-4 px-5">Severity</th>
                  <th className="py-4 px-4">Vehicle</th>
                  <th className="py-4 px-4">Alert Type</th>
                  <th className="py-4 px-4">Message</th>
                  <th className="py-4 px-4">Triggered Time</th>
                  <th className="py-4 px-5 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs text-slate-600 font-medium">
                {alerts.map((alert) => {
                  const severityClass = SEVERITY_BADGES[alert.severity] || 'bg-slate-50 border-slate-200 text-slate-600';
                  
                  return (
                    <tr key={alert.id} className="hover:bg-slate-50/50 transition-colors">
                      {/* Severity */}
                      <td className="py-4 px-5">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded text-[10px] font-extrabold uppercase border ${severityClass}`}>
                          {alert.severity}
                        </span>
                      </td>
                      {/* Vehicle */}
                      <td className="py-4 px-4">
                        <span className="font-extrabold text-slate-800">{alert.vehicle_name}</span>
                        <span className="block text-[10px] text-slate-400 font-mono mt-0.5 truncate max-w-[120px] font-semibold">
                          {alert.vehicle_id}
                        </span>
                      </td>
                      {/* Alert Type */}
                      <td className="py-4 px-4 font-mono font-bold capitalize text-slate-700">
                        {alert.type.replace('_', ' ')}
                      </td>
                      {/* Message */}
                      <td className="py-4 px-4 text-slate-700 font-semibold">{alert.message}</td>
                      {/* Time */}
                      <td className="py-4 px-4 text-slate-400">{formatDateTime(alert.created_at)}</td>
                      {/* Action */}
                      <td className="py-4 px-5 text-right">
                        <button
                          onClick={() => handleResolve(alert.id)}
                          disabled={resolvingId === alert.id}
                          className="bg-green-50 hover:bg-green-600 border border-green-200 text-green-700 hover:text-white font-bold px-3 py-1.5 rounded-xl flex items-center space-x-1.5 ml-auto transition-all duration-150 shadow-sm disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {resolvingId === alert.id ? (
                            <span className="block h-3.5 w-3.5 border-2 border-t-transparent border-slate-700 rounded-full animate-spin" />
                          ) : (
                            <Check className="h-3.5 w-3.5" />
                          )}
                          <span>Resolve</span>
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
